version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: bedrock-cost-keeper-dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - bedrock-cost-keeper-net

networks:
  bedrock-cost-keeper-net:
    driver: bridge
